### ISSUE TITLE
Onedrive sync not working

### ISSUE THREAD

**Issue by n0valis** [Jwink3101/syncrclone#12]
I have a setup with three different cloud services, two of them working flawless, Dropbox and Google Drive.
Onedrive seems to work also, no error messages, but it doesn't.
At first I get the correct info:
2021-10-18 11:57:55: A >>> B 0 files, 0.00 b
2021-10-18 11:57:56: A <<< B 960 files, 4.89 gb
but then only
2021-10-18 11:59:56: rclone: INFO  :           0 / 0 Byte, -, 0 Byte/s, ETA -
2021-10-18 12:00:56: rclone: INFO  :           0 / 0 Byte, -, 0 Byte/s, ETA -
every minute. No files copied.

rclone conf is ok
rclone copy OneDrive:OneDrive.ico /homes/xy
or
rclone copy /homes/xy/OneDrive.ico OneDrive:
working as intended.

Any thoughts?

Thanks,
Olaf

**Comment by Jwink3101** [comment]
I suspect it was rate limiting. I strongly suggest getting your own client ID. 

Glad it's working! I'm going to close this but let me know if something breaks again!

BTW, if you're using the latest, check out the `avoid_relist` option. Listing in OneDrive is slow so this is will save some time.

**Comment by n0valis** [comment]
Yes I would do that. Getting a client ID, but didn't manage to understand the process for Onedrive. Thanks to the detailed description in rclone config pages for Google drive I managed to get one for the drive account.
But I don't know what to configure for Onedrive.
I checked out https://portal.azure.com and created a client ID and a secret key. But from there on it's to complicated for me.
