### ISSUE TITLE
Create a selfupdate option to upgrade to new versions

### ISSUE THREAD

**Issue by rambalachandran** [Jwink3101/syncrclone#21]
It would be useful to implement a `selfupdate` option (similar to `rclone selfupdate`) even for the beta releases. This will help us to periodically check and upgrade the tool rather than having to check the github.

**Comment by Jwink3101** [comment]
Thanks for the suggestion. 

Self update is super useful but also fraught with security concerns. To do it right, you need to set up a way to verify (including digital signatures) the update before applying. And especially with syncrclone still technically being "beta", I am pretty hesitant. 

I could just make a command that calls the `pip ...` but that will always assume you installed with that method. 

Overall, while I appreciate the suggestion, it's not really the scope I want to accept on a (limited) hobby project. 

Thanks again!

**Comment by rambalachandran** [comment]
Well, keep the issue open if you like and hopefully it can be addressed in the future.

**Comment by Jwink3101** [comment]
I am going to close this. I am not interested in the feature at the time. Thanks for the suggestion
