### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by pschyska** [Jwink3101/syncrclone#27]
In
https://github.com/Jwink3101/syncrclone/blob/e345ff61b8254d4832f8f77b0d271eec6511332c/syncrclone/rclone.py#L77, a rclone version prefixed with `v` is expected.

My rclone version is:

```
2023-01-09 14:03:34: rclone: - go/tags: cmount%                                                                                                                                                                                        $ rclone version
rclone 1.61.1
- os/version: nixos 23.05 (Stoat) (64 bit)
- os/kernel: 6.1.3 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: dynamic
- go/tags: cmount
```

Which leads to the regex not matching. Can you make the version check more tolerant with `r"^rclone v?(.*)$"`, or can the check disabled somehow?

Cheers!

**Comment by Jwink3101** [comment]
Shoot. I guess not all versions give the same output style! 

As soon as I am on a real computer, I'll try a less regex-based way to get it and then also fall back to a warning that it can't parse. 

Sorry about that. It should be fixed this morning.

**Comment by pschyska** [comment]
> Sorry about that. It should be fixed this morning.

No worries 🙂

**Comment by pschyska** [comment]
Works, thanks!
