### ISSUE TITLE
Tries to convert a non integer version string literal into an integer

### ISSUE THREAD

**Issue by Nick-Miras** [Jwink3101/syncrclone#28]
Got this error while trying to run `syncrclone config.py`

```
2023-02-15 21:36:01: rclone: rclone v1.60.1-DEV

...

2023-02-15 21:36:01: ERROR: invalid literal for int() with base 10: '1-DEV'
```

**Comment by Jwink3101** [comment]
It’s the `-DEV` messing it up.  I am on mobile but when I am at a computer later, this is an easy fix. 

Until then, if you use a non `-DEV` version of rclone, it should work. You can always set the `rclone_exe` to point to another rclone.

**Comment by Jwink3101** [comment]
I fixed this. Between this and #27, I just made the whole version check not fail fatally if it can't parse it. There is just too much I can't control with how rclone prints version information so it will warn and move on!
