### ISSUE TITLE
Suggestion on hash compare

### ISSUE THREAD

**Issue by jjjasont** [Jwink3101/syncrclone#32]
Is it possible to have another compare option say `enforced-hash` where there's no common hash between 2 remote location, syncrclone will perform a SHA1/SHA256 calculation. And compare using the calculated hash?

### Use case: Sync between OneDrive & GDrive where there's is no common hash.

On the first run/new files, it will perform `rclone sha1sum` for the file in OneDrive and associate the SHA1/SHA256 with the QuickXorHash and saved both sha1 and QuickXorHash to the file list in the working directory.

On subsequent run, as long as the QuickXorHash from OneDrive is not changed, syncrclone will be using the saved SHA1/SHA256 to compare with the SHA1/SHA256 from GDrive.

Same concept can be used for file syncing between OneDrive & DropBox

**Comment by Jwink3101** [comment]
It is not very possible with the architecture of syncrclone.

There are essentially two approaches to bi-directional sync:

1. Compare the current state of each remote with each other and then use the past to resolve conflicts
2. Compare the current state of each remote with the past of each remote separately, the propagate changes and resolve conflicts.

Syncrclone takes the first approach. It is more robust and more closely matches how `rclone sync` works. However, it requires that each remote be compatible with each other

The second approach is what `rclone bisync` does. It would allow the features you are talking about but also introduces all kinds of issues. That is why they have all kinds of repair flags and stuff like that.

There are downsides to approach 1, including the inability to address feature requests like this, but I think it is better. 

Sorry I can't help
