### ISSUE TITLE
Rclone flags: --no-mimetype and --no-check-dest

### ISSUE THREAD

**Issue by Nynko** [Jwink3101/syncrclone#4]
Hello,
I have been encountering an issue when using syncrclone for the first time: 
```
2021-07-05 00:59:52: Refreshing file list on A '*******'
2021-07-05 00:59:52:  rclone stderr: Error: unknown flag: --no-mimetype
```
("*" were added by me) 

I have simply deleted the corresponding lines in the rclone.py file.

Then I have also had another error which doesn't show up when the lock is deactivated (so I have just done so and it works fine):
```
2021-07-05 00:52:22: Setting lock on A
2021-07-05 00:52:22: rclone: Error: unknown flag: --no-check-dest
2021-07-05 00:52:22: rclone: Usage:
2021-07-05 00:52:22: rclone:   rclone copyto source:path dest:path [flags]
...
```

I am running Ubuntu 20.04.2 LTS with a b2 remote cloud storage.
rclone v1.50.2

It is the first time I am using this tool, and I am not extremely used to rclone so it might simply be a problem on my configuration side.

Thank you !

**Comment by Jwink3101** [comment]
Those are newer flags. Please update to the latest (I think 1.55.1?) and try again. Let me know!

**Comment by Jwink3101** [comment]
> Then I have also had another error which doesn't show up when the lock is deactivated (so I have just done so and it works fine):

This is also related to a newer flag. I am 99% sure it'll work fine with the newest rclone. Either way, please let me know and I'll try to fix it.

**Comment by Nynko** [comment]
Indeed it is ^^´.
Sorry, rookie mistake...

Works fine now. Thank you !
